### ISSUE TITLE
Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file

### ISSUE THREAD

**Issue by BenjaminHoegh** [crawlzone/crawlzone#6]
`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in vendor/crawlzone/crawlzone/src/Storage/Adapter/SqliteAdapter.php:20`

how to fix this?

**Comment by ezubkevich** [comment]
Hi @BenjaminHoegh, most likely the cause of the issue is permissions. When you configure the crawler to store the progress in the file `'save_progress_in' => '/path/to/my/SQLite.db'`, the crawler tries to create the SQLite DB file in the folder you specified, and you have to make sure that the folder has the right permissions. Let me know if it helps.

**Comment by zstate** [comment]
Hi @BenjaminHoegh, most likely the cause of the issue is permissions. When you configure the crawler to store the progress in the file 'save_progress_in' => '/path/to/my/SQLite.db', the crawler tries to create the SQLite DB file in the folder you specified, and you have to make sure that the folder has the right permissions. Let me know if it helps.

**Comment by zstate** [comment]
Let me know if you have any other issues.
